import type {Metadata} from "next";
import "./global.scss";

export const metadata: Metadata = {
    title: "Blog Page",
    description: "Generated by create next app",
};

export default function BlogLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
    <div>
        <aside>Боковая панель блога</aside>
        <main>{children}</main>
    </div>
);
}