// import type {Metadata} from "next";
import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";
import "./styles/globals.scss";

// export const metadata: Metadata = {
//     title: "JENNA",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className="root">
        <Header />
            <main className="">
                {children}
            </main>
        <Footer />
        </body>
        </html>
    );
}
