import type {Metadata} from "next";
import "./styles/globals.scss";
import NavLinks from "@/components/NavLinks";

export const metadata: Metadata = {
    title: "Main Page",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body>
        <header>
            <NavLinks />
        </header>
        {children}
        </body>
        </html>
    );
}
